import { ethers } from "hardhat";
import * as fs from "node:fs";
import * as path from "node:path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deployer:", deployer.address);
  console.log(
    "Balance:",
    ethers.formatEther(await ethers.provider.getBalance(deployer.address)),
    "ETH",
  );

  const initialSupply = ethers.parseEther("1000000");
  const token = await ethers.deployContract("AetherToken", [
    deployer.address,
    initialSupply,
  ]);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("AetherToken:", tokenAddress);

  const guestbook = await ethers.deployContract("Guestbook");
  await guestbook.waitForDeployment();
  const guestbookAddress = await guestbook.getAddress();
  console.log("Guestbook:", guestbookAddress);

  const network = await ethers.provider.getNetwork();
  const snippet = [
    `# Generated by deploy script (${new Date().toISOString()})`,
    `# chainId=${network.chainId.toString()} deployer=${deployer.address}`,
    `VITE_GUESTBOOK_ADDRESS=${guestbookAddress}`,
    `VITE_AETHER_TOKEN_ADDRESS=${tokenAddress}`,
    `VITE_SEPOLIA_RPC_URL=${process.env.SEPOLIA_RPC_URL || "https://rpc.sepolia.org"}`,
    "",
  ].join("\n");

  console.log("\n--- copy into apps/dapp/.env ---\n");
  console.log(snippet);

  const outDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(
    outDir,
    `sepolia-${network.chainId.toString()}.env.snippet`,
  );
  fs.writeFileSync(outFile, snippet, "utf8");
  console.log(`Wrote ${outFile}`);
  console.log(
    "Also set the same VITE_* vars in Vercel → Redeploy for the live demo.",
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
